[package]
name = "miso"
version = "0.1.0"
edition = "2024"

[dependencies]

[dev-dependencies]
criterion = { version = "0.7.0", features = ["html_reports"] }
rand = "0.9.2"

[[bench]]
name = "hashmap_workloads"
harness = false

[profile.bench]
opt-level = 3            # maximum optimization
lto = "thin"             # ThinLTO: good speed/compile-time tradeoff
codegen-units = 1        # better cross-module inlining
debug = false            # no debug symbols (smaller, slightly faster)
debug-assertions = false # remove runtime debug checks
